### ISSUE TITLE
Don't commit node_modules

### ISSUE THREAD

**Issue by walane** [NaveenKarippai/hybrid-weather#1]
Please don't commit node_module inside app folder :
- Because too heavy to download
- Because it cause a failure on npm start (electron-prebuilt called from your local user home directory /home/naveenkarippai/)

Thank you :)

**Comment by NaveenKarippai** [comment]
Yes, true and thanks. It was a noob mistake from my side. 

I had an idea to revert the whole repo (by adding better commit messages + gitignore [npm_modules, built app] ) to bring new life to project itself.

Glad that you pointed it out! @walane

**Comment by walane** [comment]
No problem have a nice evening :)

**Comment by NaveenKarippai** [comment]
So, I just rewrote commit history. 
This project was sleeping for a long time and had a thought today about giving new life to this project by shaping it from a weather app to desktop app for imgur.
